config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cart_line_items
  resources :shopping_carts
  resources :user_profiles
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  resources :prod_categories
  get 'dashboard/index'
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'contact/index'
  get '/about/index'
  get 'home/index'
  get '/about/edit'
  get 'product/index'
  get 'categories/index'
  get '/categories/:id', to: 'categories#show', as: 'category'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  resources :products, :home, :about, :contact, :dashboard, :categories, :orders, :carts
  root 'home#index'

  # button_to "Add to cart", line_items_path(:product_id => product.id)

  # link_to "Add (+1)", line_item_add_path(:id => line_item), method: :post
  # link_to "Reduce (-1)", line_item_reduce_path(:id => line_item), method: :post
  # link_to "Remove item", line_item_path(line_item), method: :delete

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
end

app/models/cart_line_item.rb
# frozen_string_literal: true

class CartLineItem < ApplicationRecord
  belongs_to :product
  belongs_to :ShoppingCart
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :categoryId, :name, presence: true
  validates :categoryId, numericality: true
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
end

app/models/prod_category.rb
# frozen_string_literal: true

class ProdCategory < ApplicationRecord
  has_many :products
  validates :categoryId, :name, presence: true
  validates :categoryId, numericality: true
end

app/models/product.rb
# frozen_string_literal: true

# product model
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  mount_uploader :image, ImageUploader
  serialize :image, JSON
  has_many :cart_line_items
  validates :name, :manufacturer, :price, :stock, :description, :weight, :categoryId, presence: true
  validates :stock, :weight, :categoryId, numericality: true

  def self.search(search)
    if search
      product_type = Product.find_by(name: search)
      if product_type
        where(product_id: product_type, role: search[:":role"][","])
      else
        @products = Product.all
      end
    else
      @products = Product.all
    end
  end

  private

  def not_referenced_by_any_line_item
    return if cart_line_items.empty?

    errors.add(:base, "Line items present")
    throw :abort
  end
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
end

app/models/shopping_cart.rb
# frozen_string_literal: true

# shopping cart model
class ShoppingCart < ApplicationRecord
  has_many :cart_line_items, dependent: :destroy

  def add_product(product)
    current_item = cart_line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = cart_line_items.build(product_id: product.id)
    end
    current_item
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # def cart_count
  #   $redis.scard "cart#{id}"
  # end
end

app/models/user_profile.rb
# frozen_string_literal: true

class UserProfile < ApplicationRecord
end

app/controllers/prod_categories_controller.rb
# frozen_string_literal: true

# Controller that contains the methods for the product categories
# - Use this instead of regular categories
class ProdCategoriesController < ApplicationController
  before_action :set_prod_category, only: %i[show edit update destroy]

  # GET /prod_categories or /prod_categories.json
  def index
    @prod_categories = ProdCategory.all
    @products = Product.all
  end

  # GET /prod_categories/1 or /prod_categories/1.json
  def show; end

  # GET /prod_categories/new
  def new
    @prod_category = ProdCategory.new
  end

  # GET /prod_categories/1/edit
  def edit; end

  # POST /prod_categories or /prod_categories.json
  def create
    @prod_category = ProdCategory.new(prod_category_params)

    respond_to do |format|
      if @prod_category.save
        format.html do
          redirect_to prod_category_url(@prod_category),
                      notice: "Prod category was successfully created."
        end
        format.json { render :show, status: :created, location: @prod_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prod_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prod_categories/1 or /prod_categories/1.json
  def update
    respond_to do |format|
      if @prod_category.update(prod_category_params)
        format.html do
          redirect_to prod_category_url(@prod_category),
                      notice: "Prod category was successfully updated."
        end
        format.json { render :show, status: :ok, location: @prod_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prod_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prod_categories/1 or /prod_categories/1.json
  def destroy
    @prod_category.destroy

    respond_to do |format|
      format.html do
        redirect_to prod_categories_url, notice: "Prod category was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_prod_category
    @prod_category = ProdCategory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def prod_category_params
    params.require(:prod_category).permit(:name, :categoryId)
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

# controller helper for the about page
module AboutHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  # helper for cart controller
  class Cart < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items

    # LOGIC
    def sub_total
      sum = 0
      line_items.each do |line_item|
        sum += line_item.total_price
      end
      sum
    end
  end
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

# controller helper for contact page
module ContactHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

# controller helper for dashboard page
module DashboardHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# controller helper for home page
module HomeHelper
end

app/helpers/line_items_helper.rb
# frozen_string_literal: true

# helper for line items controller
module LineItemsHelper
  # class of helper for line item controller
  class LineItem < ActiveRecord::Base
    belongs_to :product
    belongs_to :cart
    belongs_to :order

    # LOGIC
    def total_price
      quantity * product.price
    end
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# hepler for orders controller
module OrdersHelper
end

app/helpers/prod_categories_helper.rb
# frozen_string_literal: true

# helper for prod categories controller
module ProdCategoriesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# helper for products controller
module ProductsHelper
  def allow_product_add?(_product)
    return false unless current_user

    @product.user_id == current_user.id
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/prod_categories/_form.html.erb
<%= form_with(model: prod_category) do |form| %>
  <% if prod_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prod_category.errors.count, "error") %> prohibited this prod_category from being saved:</h2>

      <ul>
        <% prod_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :categoryId, style: "display: block" %>
    <%= form.number_field :categoryId %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prod_categories/_prod_category.html.erb
<div id="<%= dom_id prod_category %>">
  <p>
    <strong>Name:</strong>
    <%= prod_category.name %>
  </p>

  <p>
    <strong>Categoryid:</strong>
    <%= prod_category.categoryId %>
  </p>

</div>

app/views/prod_categories/edit.html.erb
<h1>Editing prod category</h1>

<%= render "form", prod_category: @prod_category %>

<br>

<div>
  <%= link_to "Show this prod category", @prod_category %> |
  <%= link_to "Back to prod categories", prod_categories_path %>
</div>

app/views/prod_categories/index.html.erb
<div class="content">

  <p style="color: green"><%= notice %></p>

  <div class="box">

    <div class="title">Categories</div>


    <div id="categories" class="list">
      <ul>
        <% @prod_categories.each do |category| %>
            <li><%= link_to category.name , category %></li>
        <% end %>
      </ul>
    </div>
  </div>

</div>

app/views/prod_categories/new.html.erb
<h1>New prod category</h1>

<%= render "form", prod_category: @prod_category %>

<br>

<div>
  <%= link_to "Back to prod categories", prod_categories_path %>
</div>

app/views/prod_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render @prod_category %> 


<div class="box">
  <div class="title"><%= @prod_category.name %></div>

    <% if @prod_category.name === "None"%>
        <div id="products" class="container">
            <% Product.all.each do |product| %>
            
            <div class="card">
                <div class="card-content">
                    <% if product.image.url %>
                        <%= image_tag product.image.url %>
                    <% end %>
                    <%= link_to product.manufacturer + " - " + product.name , product %>
                    <br>
                    CAD <%= number_to_currency(product.price) %>
                </div>
            </div>
            <% end %>
        </div>
    <% else %>    
        <div id="products" class="container">
            <% Product.where(categoryId: (@prod_category.categoryId - 1)).each do |product| %>
            
            <div class="card">
                <div class="card-content">
                <% if product.image.url %>
                    <%= image_tag product.image.url %>
                <% end %>
                <%= link_to product.manufacturer + " - " + product.name , product %>
                <br>
                CAD <%= number_to_currency(product.price) %>
                </div>
            </div>
            <% end %>
        </div>
    <% end %>

</div>