config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cart_line_items
  resources :shopping_carts
  resources :user_profiles
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  resources :prod_categories
  get 'dashboard/index'
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'contact/index'
  get '/about/index'
  get 'home/index'
  get '/about/edit'
  get 'product/index'
  get 'categories/index'
  get '/categories/:id', to: 'categories#show', as: 'category'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  resources :products, :home, :about, :contact, :dashboard, :categories, :orders, :carts
  root 'home#index'

  # button_to "Add to cart", line_items_path(:product_id => product.id)

  # link_to "Add (+1)", line_item_add_path(:id => line_item), method: :post
  # link_to "Reduce (-1)", line_item_reduce_path(:id => line_item), method: :post
  # link_to "Remove item", line_item_path(line_item), method: :delete

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
end

app/models/cart_line_item.rb
# frozen_string_literal: true

class CartLineItem < ApplicationRecord
  belongs_to :product
  belongs_to :ShoppingCart
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :categoryId, :name, presence: true
  validates :categoryId, numericality: true
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
end

app/models/prod_category.rb
# frozen_string_literal: true

class ProdCategory < ApplicationRecord
  has_many :products
  validates :categoryId, :name, presence: true
  validates :categoryId, numericality: true
end

app/models/product.rb
# frozen_string_literal: true

# product model
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  mount_uploader :image, ImageUploader
  serialize :image, JSON
  has_many :cart_line_items
  validates :name, :manufacturer, :price, :stock, :description, :weight, :categoryId, presence: true
  validates :stock, :weight, :categoryId, numericality: true

  def self.search(search)
    if search
      product_type = Product.find_by(name: search)
      if product_type
        where(product_id: product_type, role: search[:":role"][","])
      else
        @products = Product.all
      end
    else
      @products = Product.all
    end
  end

  private

  def not_referenced_by_any_line_item
    return if cart_line_items.empty?

    errors.add(:base, "Line items present")
    throw :abort
  end
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
end

app/models/shopping_cart.rb
# frozen_string_literal: true

# shopping cart model
class ShoppingCart < ApplicationRecord
  has_many :cart_line_items, dependent: :destroy

  def add_product(product)
    current_item = cart_line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = cart_line_items.build(product_id: product.id)
    end
    current_item
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # def cart_count
  #   $redis.scard "cart#{id}"
  # end
end

app/models/user_profile.rb
# frozen_string_literal: true

class UserProfile < ApplicationRecord
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# Controller for the category definitions
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to category_url(@category), notice: "category was successfully created."
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to category_url(@category), notice: "category was successfully updated."
        end
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:id, :name, :categoryId)
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

# controller helper for the about page
module AboutHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  # helper for cart controller
  class Cart < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items

    # LOGIC
    def sub_total
      sum = 0
      line_items.each do |line_item|
        sum += line_item.total_price
      end
      sum
    end
  end
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

# controller helper for contact page
module ContactHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

# controller helper for dashboard page
module DashboardHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# controller helper for home page
module HomeHelper
end

app/helpers/line_items_helper.rb
# frozen_string_literal: true

# helper for line items controller
module LineItemsHelper
  # class of helper for line item controller
  class LineItem < ActiveRecord::Base
    belongs_to :product
    belongs_to :cart
    belongs_to :order

    # LOGIC
    def total_price
      quantity * product.price
    end
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# hepler for orders controller
module OrdersHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# helper for products controller
module ProductsHelper
  def allow_product_add?(_product)
    return false unless current_user

    @product.user_id == current_user.id
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Id:</strong>
    <%= category.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>


</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :categoryId, style: "display: block" %>
    <%= form.number_field :categoryId %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<head>
   <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
</head>

<div class="content">

  <p style="color: green"><%= notice %></p>

  <div class="title">Categories</div>


  <div id="categories" class="container">
    <ul>
        <% @categories.each do |category| %>
            <li><%= link_to category.name , category %></li>

        <% end %>
    </ul>
  </div>

</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render @product %> 

<div class="box">
  <div class="title"><%= @category.name %></div>

    <% if @category.id === 1 %>
        <div id="products" class="container">
            <% Product.all.each do |product| %>
            
            <div class="card">
                <div class="card-content">
                <%= link_to product.manufacturer + " - " + product.name , product %>
                <br>
                CAD <%= number_to_currency(product.price) %>
                </div>
            </div>
            <% end %>
        </div>
    <% else %>    
        <div id="products" class="container">
            <% Product.where(categoryId: (@category.id - 1)).each do |product| %>
            
            <div class="card">
                <div class="card-content">
                <%= link_to product.manufacturer + " - " + product.name , product %>
                <br>
                CAD <%= number_to_currency(product.price) %>
                </div>
            </div>
            <% end %>
        </div>
    <% end %>

    
    
    

  <%# <% if current_user %>
    <%# <% if current_user.id === 1 %>
      <%# <div>
        <%= link_to "Edit this product", edit_product_path(@product) %> 
        <%# <%= link_to "Back to products", products_path %> 

        <%# <%= button_to "Destroy this product", @product, method: :delete %> 
      <%# </div> %> 
    <%# <% end %> 
  <%# <% end %>  

</div>