config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cart_line_items
  resources :shopping_carts
  resources :user_profiles
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  resources :prod_categories
  get 'dashboard/index'
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'contact/index'
  get '/about/index'
  get 'home/index'
  get '/about/edit'
  get 'product/index'
  get 'categories/index'
  get '/categories/:id', to: 'categories#show', as: 'category'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  resources :products, :home, :about, :contact, :dashboard, :categories, :orders, :carts
  root 'home#index'

  # button_to "Add to cart", line_items_path(:product_id => product.id)

  # link_to "Add (+1)", line_item_add_path(:id => line_item), method: :post
  # link_to "Reduce (-1)", line_item_reduce_path(:id => line_item), method: :post
  # link_to "Remove item", line_item_path(line_item), method: :delete

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
# frozen_string_literal: true

# product model
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  mount_uploader :image, ImageUploader
  serialize :image, JSON
  has_many :cart_line_items
  validates :name, :manufacturer, :price, :stock, :description, :weight, :categoryId, presence: true
  validates :stock, :weight, :categoryId, numericality: true

  def self.search(search)
    if search
      product_type = Product.find_by(name: search)
      if product_type
        where(product_id: product_type, role: search[:":role"][","])
      else
        @products = Product.all
      end
    else
      @products = Product.all
    end
  end

  private

  def not_referenced_by_any_line_item
    return if cart_line_items.empty?

    errors.add(:base, "Line items present")
    throw :abort
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Controller for the products. Contains methods used for manipulating the products.
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :initialize_session

  # GET /products or /products.json
  def index
    @current_user = current_user
    @prod_categories = ProdCategory.all

    if params[:search]
      @products = Product.where(["name LIKE ? or categoryId LIKE ?", "%#{params[:search]}%",
                                 "%#{params[:categoryId]}%"]).page(params[:page])
      @products = Kaminari.paginate_array(@products).page(params[:page]).per(10)
    else
      @products = Product.page(params[:page])
    end
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to cart_path
    flash[:notice] = "Item added to cart"
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to cart_path
    flash[:notice] = "Item was removed from cart"
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # def product_params
  #   params.require(:product).permit(:name, categories.name, :manufacturer, :search, :categoryId)
  # end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html do
          redirect_to product_url(@product)
        end
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to product_url(@product), notice: "Product was successfully updated."
        end
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:id, :name, :manufacturer, :price,
                                    :stock, :description, :weight, :categoryId, :image)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# helper for products controller
module ProductsHelper
  def allow_product_add?(_product)
    return false unless current_user

    @product.user_id == current_user.id
  end
end

app/views/products/_form.html.erb
<%= simple_form_for @product, html: { multipart: true } do |form| %>
      <%= form.error_notification %>

  <%# <%= form_with(model: product) do |form| %>
    <%# <% if product.errors.any? %> 
      <%# <div style="color: red"> %>
        <%# <h2><%= pluralize(product.errors.count, "error") prohibited this product from being saved:</h2> %> 

        <%# <ul> %>
          <%# <% product.errors.each do |error| %> 
            <%# <li><%= error.full_message</li> %>
          <%# <% end %>
        <%# </ul> %>
      <%# </div> %>
    <%# <% end %> 

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :manufacturer, style: "display: block" %>
    <%= form.text_field :manufacturer %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :categoryId, style: "display: block" %>
    <%= form.number_field :categoryId %>
  </div>

  <div class="control">
    <label class="label">Add images</label>
      <div class="file">
      <label class="file-label">
        <%= form.input :image, as: :file, input_html: { class:"file-input product-image" }, label: false, wrapper: false %>
          <span class="file-cta">
            <span class="file-icon"><i class="fa fa-upload"></i></span>
            <span class="file-label">Choose a file…</span>
          </span>
      </label>
      </div>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Id:</strong>
    <%= product.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Manufacturer:</strong>
    <%= product.manufacturer %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= product.stock %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= product.weight %>
  </p>

  <p>
    <strong>Categoryid:</strong>
    <%= product.categoryId %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<%# <%= debug session[:cart] %> 

<div class="content">

  <p style="color: green"><%= notice %></p>

  <div class="title">Products</div>


  <div class="box">
    <%= form_tag(products_path, method: :get) do %>
      <select name="category" class="form-control">
        <% @prod_categories.each do |category| %>
          <option value="<%= category.id %>"><%= category.name %></option>
        <% end %>
      </select>
      <%= text_field_tag(:search, params[:search]) %>
      
      <%= submit_tag ("Search") %>
    <% end %>
  </div>

  <br>

  <div id="products" class="container">
    
    <% @products.each do |product| %>
      
      <div class="card">
        <div class="card-content">
          <% if product.image.url %>
            <%= image_tag product.image.url, alt:product.image.url %>
          <% end %>
          <%= link_to product.manufacturer + " - " + product.name , product %>
          <br>
          CAD <%= number_to_currency(product.price) %>
        </div>
      </div>
    <% end %>
  </div>


  <div id="paginate">
    <%= paginate @products %>
  </div> 

</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render @product %> 

<div class="box">
  <% if @product.image.url %>
    <%= image_tag @product.image.url, alt:@product.image.url %>
  <% end %>

  <div class="title"><%= @product.manufacturer + " - " + @product.name %></div>

  <div class="subtitle"><%= number_to_currency(@product.price) %></div>

  <div class="content"><%= @product.description %></div>

  <div class="content"><strong>Weight: </strong> <%= @product.weight %>oz</div>

  <div class="content"><strong>Stock on hand: </strong> <%= @product.stock %> units</div>


  <p><%= link_to 'Add to Cart', add_to_cart_path(@product.id), method: :post %></p>

  <br>
  
  <%= social_share_button_tag(@product.name) %>
  <%# <p><%= link_to 'Add to Cart', cart_line_items_path(product_id: @product.id), method: :post %>

  <%# <% if current_user %>
    <%# <% if current_user.id === 1 %>
      <%# <div>
        <%= link_to "Edit this product", edit_product_path(@product) %> 
        <%# <%= link_to "Back to products", products_path %> 

        <%# <%= button_to "Destroy this product", @product, method: :delete %> 
      <%# </div> %> 
    <%# <% end %> 
  <%# <% end %>  

</div>